# Generated by Django 4.2.4 on 2023-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Region1',
            },
        ),
    ]
