# Generated by Django 4.2.4 on 2023-08-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0002_region1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news1',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news1.region1'),
        ),
    ]
