# Generated by Django 4.2.2 on 2023-08-30 12:04

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news1', '0003_alter_news1_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news1',
            options={'ordering': ['-created'], 'verbose_name_plural': 'News1'},
        ),
        migrations.AlterField(
            model_name='news1',
            name='reporter',
            field=models.ForeignKey(default=django.contrib.auth.get_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
