# Generated by Django 4.2.4 on 2023-08-30 13:04

import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0004_alter_news1_options_alter_news1_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news1',
            name='photographer',
            field=models.CharField(default=django.contrib.auth.get_user_model, max_length=100),
        ),
        migrations.AlterField(
            model_name='category1',
            name='tagline',
            field=models.TextField(max_length=200),
        ),
    ]
