# Generated by Django 4.2.4 on 2023-08-30 13:07

import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0005_news1_photographer_alter_category1_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news1',
            name='photographer',
            field=models.CharField(default=django.contrib.auth.get_user, max_length=100),
        ),
    ]
