# Generated by Django 4.2.4 on 2023-09-06 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news1', '0006_alter_news1_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news1',
            name='photographer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news1',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
