# Generated by Django 4.2.4 on 2023-09-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='slidernews',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news2.category'),
        ),
    ]
