# Generated by Django 4.2.4 on 2023-09-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0003_alter_category_options_alter_slidernews_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidernews',
            old_name='tagline',
            new_name='headline',
        ),
    ]
