# Generated by Django 4.2.4 on 2023-09-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0004_rename_tagline_slidernews_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidernews',
            old_name='headline',
            new_name='content',
        ),
    ]
