# Generated by Django 4.2.4 on 2023-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0005_rename_headline_slidernews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidernews',
            name='headline',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slidernews',
            name='content',
            field=models.TextField(),
        ),
    ]
