# Generated by Django 4.2.4 on 2023-09-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0009_delete_breakingnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='News2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('published', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'News2',
            },
        ),
    ]
