# Generated by Django 4.2.4 on 2023-09-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0011_newsletter_delete_news2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
