# Generated by Django 4.2.4 on 2023-09-15 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news2', '0012_enquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidernews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
