# Generated by Django 4.2.4 on 2023-09-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news2',
            options={'verbose_name_plural': 'News2'},
        ),
    ]
